### PR TITLE
Fix duplicated filename in reference when using write_reference_line_numbers

### LINKED ISSUE #344: Duplicate Filename in Reference when `:write_reference_line_numbers` is set to `false`
When the `:write_reference_line_numbers` option is set to `false`, the line numbers are removed from the references as expected. However, when the same string is used multiple times in one file, the filename is duplicated in the reference. Is this the expected behavior?

The current POT output is:
```
#: lib/test/templates/home.html.heex
#: lib/test/templates/home.html.heex
#, elixir-autogen, elixir-format
msgid "%{product_name} video"
msgstr ""
```

The expected POT output is:
```
#: lib/test/templates/home.html.heex
#, elixir-autogen, elixir-format
msgid "%{product_name} video"
msgstr ""
```

### PR DESCRIPTION
**Pull request by agenestar**
Fixes #344

### CODE REVIEW

File: test/gettext/merger_test.exs [hunk 1]
```diff
@@ -492,7 +492,13 @@ defmodule Gettext.MergerTest do
     test "prunes reference line numbers when `write_reference_line_numbers` is `false`" do
       po = %Messages{
         messages: [
-          %Message.Singular{msgid: "a", references: [[{"path/to/file.ex", 12}]]},
+          %Message.Singular{
+            msgid: "a",
+            references: [
+              [{"path/to/file.ex", 12}, {"path/to/file.ex", 24}],
+              [{"path/to/other_file.ex", 24}]
```
Comment (maennchen) [inline test/gettext/merger_test.exs:499]: How does this behave with this?

```suggestion
              [{"path/to/file.ex", 12}, {"path/to/file.ex", 24}],
              [{"path/to/file.ex", 42}],
              [{"path/to/other_file.ex", 24}]
```

Comment (agenestar) [reply test/gettext/merger_test.exs]: Thanks for your help! It fails with these modifications. 

I have added your suggestion and modified the function to have unique filenames also at the reference level. Im not 100% sure about the code style in the prune_references function but it is working right now.

Comment (agenestar) [reply test/gettext/merger_test.exs]: Sorry, but it is my first contribution to gettext. Can you give me an example of a scenario where this could happen?

Comment (maennchen) [reply test/gettext/merger_test.exs]: Sure :)

Gettext should be able to handle any valid `.po` file. This is valid:

```elixir
Mix.install([{:expo, "~> 0.2"}])

"""
#: file:1 file:2
#: file:3
#: other_file:1
msgid "how are you," " friend?"
msgstr "come stai,"
"""
|> Expo.PO.parse_string!()
|> dbg()
```

```
[example.exs:11: (file)]
"#: file:1 file:2\n#: file:3\n#: other_file:1\nmsgid \"how are you,\" \" friend?\"\nmsgstr \"come stai,\"\n" #=> "#: file:1 file:2\n#: file:3\n#: other_file:1\nmsgid \"how are you,\" \" friend?\"\nmsgstr \"come stai,\"\n"
|> Expo.PO.parse_string!() #=> %Expo.Messages{
  headers: [],
  messages: [
    #Expo.Message.Singular<
      msgid: ["how are you,", " friend?"],
      msgstr: ["come stai,"],
      msgctxt: nil,
      comments: [],
      extracted_comments: [],
      flags: [],
      previous_messages: [],
      references: [
        [{"file", 1}, {"file", 2}],
        [{"file", 3}],
        [{"other_file", 1}]
      ],
      obsolete: false,
      ...
    >
  ],
  top_comments: [],
  file: nil
}
```

As long as gettext is the creator of a message, that will normally not happen, because it automatically puts every reference on a new line:

https://github.com/elixir-gettext/gettext/blob/2ebe8066d6309ea2d810beb93e38433fef6f5071/lib/gettext/extractor.ex#L186

There's however also `.po` editors out there that decide the line splitting based on the line width. So it is fully possible that a file contains those kind of entries after it has been handled by an outside tool.

File: lib/gettext/merger.ex [hunk 2]
```diff
@@ -252,40 +252,45 @@ defmodule Gettext.Merger do
         put_in(all, [Access.key!(:messages), Access.all(), Access.key(:references)], [])
 
       not write_line_numbers? ->
-        lines_accessor = [
+        all.messages
```
Comment (maennchen) [inline lib/gettext/merger.ex:255]:
```suggestion
```

**Review by maennchen — CHANGES_REQUESTED** [review]

**Review by maennchen — APPROVED** [review]

**Comment by agenestar** [comment]
Thanks @maennchen for your help :)
